/*sidebarConf配置文件*/
module.exports = {
  // 侧边栏在 /index/ 目录上
  '/work/': [
    ['task','计划'],
    ['account','账号'],
    ['travel','旅行'],
  ],
  '/vue/': [
    ['vueCreate','vue项目搭建'],
    ['vueSummary','vue总结'],
    ['communication','vue组件通信'],
    ['vuex','vuex使用'],
    ['vueSlot','vue插槽'],
    ['customDirectives','自定义指令和插件'],
    ['eslint','eslint'],
    ['element_ui','element-ui'],
    ['WebSocket','WebSocket'],
  ],
  '/js/': [
    ['es6','es6使用手册'],
    ['async','js异步'],
    ['prototype','原型与原型链'],
    ['json','json使用'],
    ['regex','正则表达式'],
    ['operator','js运算符'],
    ['array','数组'],
    ['node','node使用'],
    ['npm','npm使用'],
    ['typescript','typescript'],
  ],
  '/css/': [
    ['often','常用样式'],
    ['button','按钮'],
    ['listLayout','列表布局'],
    ['add','css加号'],
    ['ellipsis','文本省略号'],
    ['radio','radio和checkbox'],
    ['bottomFixing','css实现底部固定'],
  ],
  '/mobile/': [
    ['rem','rem适配'],
    ['reset','去除默认样式'],
    ['smallProgram','小程序'],
  ],
  '/tools/': [
    ['MongoDB','MongoDB'],
    ['mysql','mysql入门'],
    ['python','python'],
    ['selenium','selenium使用'],
    ['gitlib','gitlib安装'],
    ['xmind','xmind'],
    ['nginx','nginx开机自启'],
    ['WMware','WMware'],
    ['git','git使用'],
    ['Webstorm','Webstorm'],
    ['VisualStudioCode','VisualStudioCode'],
    ['linux','linux'],
    ['linux_common','linux常用命令']
  ],
}