/*sidebarConf配置文件*/
module.exports = {
  // 侧边栏在 /index/ 目录上
  '/work/': [
    '计划',
    '账号',
    '加班'
  ],
  '/vue/': [
    '项目常用模板',
    'vite搭建vue3项目',
    'app项目升级',
    'crm项目升级',
    'vue2升级vue3',
    'vue项目搭建',
    'stylelint',
    'eslint',
    'git提交规范',
    'vuex使用',
    'vue总结1',
    'vue总结2',
    'token刷新',
    '自定义指令',
    'element_ui',
    '阿里矢量图标'
  ],
  '/js/': [
    ['es6','es6使用手册'],
    ['es11','es11使用手册'],
    ['async','js异步'],
    ['prototype','原型与原型链'],
    ['json','json使用'],
    ['regex','正则表达式'],
    ['operator','js运算符'],
    ['array','数组'],
    ['node','node使用'],
    ['npm','npm使用'],
    'pnpm使用',
    ['typescript','typescript'],
  ],
  '/css/': [
    ['often','常用样式'],
    ['flex','flex布局'],
    ['button','按钮'],
    ['listLayout','列表布局'],
    ['add','css加号'],
    ['ellipsis','文本省略号'],
    ['radio','radio和checkbox'],
    ['bottomFixing','css实现底部固定'],
  ],
  '/mobile/': [
    ['rem','rem适配'],
    ['reset','去除默认样式'],
    'uniapp',
    '小程序',
  ],
  '/tools/': [
    'nvm',
    'vscode',
    'R4S',
    'iStoreOS',
    'clash',
    ['MongoDB','MongoDB'],
    ['mysql','mysql入门'],
    ['python','python'],
    ['selenium','selenium使用'],
    ['gitlib','gitlib安装'],
    ['xmind','xmind'],
    ['nginx','nginx开机自启'],
    ['WMware','WMware'],
    ['git','git使用'],
    ['Webstorm','Webstorm'],
    ['linux','linux'],
    ['linux_common','linux常用命令'],
    '新手技巧'
  ],
  '/other/': [
    '修改Git提交记录',
    'jenkins自动部署',
    'typescript基础类型',
    'typescript快速入门',
    'vue自动部署',
    'webpack教程',
    'webpack起步'
  ]
}
